In [1]:
bitcoin_words = [
    "BITCOIN",
    "BTC",
    "HALVING"
]

In [2]:
altcoin_words = [
    "ALTCOIN",
    "XRP",
    "ADA",
    "ETH",
    "SOL"
]

In [3]:
trading_words = [
    "FUTURES",
    "TRADING",
    "STOP LOSS",
    "FIBONACCI"
]

In [4]:
exchange_words = [
    "BINANCE",
    "BYBIT",
    "ZONDA"
]

In [5]:
macro_words = [
    "USA",
    "TRUMP",
    "IRAN",
    "WOJNA"
]

In [6]:
df.groupby("bitcoin_topic")[
    [
        "view_count",
        "comment_count",
        "engagement_rate"
    ]
    ].mean()

NameError: name 'df' is not defined

In [9]:
df["bitcoin_words"].value_counts()

NameError: name 'df' is not defined

In [10]:
import pandas as pd

df = pd.read_csv(
    "data/processed/master_dataset_with_title_features.csv"
)

print(df.shape)

(696, 52)

In [11]:
df.columns.tolist()

['video_id',
 'title',
 'published_at',
 'description',
 'channel_title',
 'category_id',
 'duration',
 'view_count',
 'like_count',
 'comment_count',
 'year_x',
 'month_x',
 'month_name_x',
 'duration_minutes',
 'engagement_rate',
 'weekday_x',
 'weekday_num',
 'publish_hour',
 'publish_year_month',
 'like_rate',
 'comment_rate',
 'upload_date',
 'Unix',
 'Date',
 'Symbol',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume BTC',
 'Volume USDT',
 'tradecount',
 'daily_return',
 'volatility_7d',
 'ma_7',
 'ma_30',
 'ma_90',
 'bull_market',
 'year_y',
 'month_y',
 'month_name_y',
 'weekday_y',
 'market_regime',
 'btc_date',
 'volatility_bucket',
 'title_length',
 'title_word_count',
 'fear_title',
 'curiosity_title',
 'opportunity_title',
 'conflict_title',
 'fear_curiosity_title']

In [12]:
df.groupby("bitcoin_topic")

KeyError: 'bitcoin_topic'

In [13]:
df["bitcoin_topic"]

KeyError: 'bitcoin_topic'

In [14]:
def contains_any_word(title, words):
    title = str(title).upper()
    return any(word in title for word in words)

In [15]:
df["bitcoin_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, bitcoin_words)
)

df["altcoin_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, altcoin_words)
)

df["trading_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, trading_words)
)

df["exchange_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, exchange_words)
)

df["macro_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, macro_words)
)

In [16]:
df[
    [
        "bitcoin_topic",
        "altcoin_topic",
        "trading_topic",
        "exchange_topic",
        "macro_topic"
    ]
].sum()

bitcoin_topic     150
altcoin_topic     101
trading_topic      68
exchange_topic     37
macro_topic        36
dtype: int64

In [17]:
df.groupby("bitcoin_topic")[
    [
        "view_count",
        "comment_count",
        "engagement_rate"
    ]
].mean()

                 view_count  comment_count  engagement_rate
bitcoin_topic
False          11564.230769      52.010989         0.049553
True           10363.460000      47.800000         0.058038

In [18]:
topic_columns = [
    "bitcoin_topic",
    "altcoin_topic",
    "trading_topic",
    "exchange_topic",
    "macro_topic"
]

for topic in topic_columns:
    print("\n" + topic)
    display(
        df.groupby(topic)[
            [
                "view_count",
                "comment_count",
                "engagement_rate"
            ]
        ].mean()
    )

bitcoin_topic

                 view_count  comment_count  engagement_rate
bitcoin_topic
False          11564.230769      52.010989         0.049553
True           10363.460000      47.800000         0.058038

altcoin_topic

                 view_count  comment_count  engagement_rate
altcoin_topic
False          11330.820168      51.157983         0.050773
True           11155.950495      50.782178         0.054969

trading_topic

                 view_count  comment_count  engagement_rate
trading_topic
False          11365.199045      52.694268         0.051761
True           10753.588235      36.411765         0.047882

exchange_topic

                  view_count  comment_count  engagement_rate
exchange_topic
False           10978.244310      48.379363         0.051915
True            17133.135135      99.621622         0.041888

macro_topic

               view_count  comment_count  engagement_rate
macro_topic
False        11169.057576      50.993939         0.051992
True         13805.861111      53.111111         0.040199