In [2]:
import pandas as pd

df = pd.read_csv(
    "data/processed/master_dataset_with_title_features.csv"
)

print(df.shape)

(696, 52)

In [3]:
df.columns.tolist()

['video_id',
 'title',
 'published_at',
 'description',
 'channel_title',
 'category_id',
 'duration',
 'view_count',
 'like_count',
 'comment_count',
 'year_x',
 'month_x',
 'month_name_x',
 'duration_minutes',
 'engagement_rate',
 'weekday_x',
 'weekday_num',
 'publish_hour',
 'publish_year_month',
 'like_rate',
 'comment_rate',
 'upload_date',
 'Unix',
 'Date',
 'Symbol',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume BTC',
 'Volume USDT',
 'tradecount',
 'daily_return',
 'volatility_7d',
 'ma_7',
 'ma_30',
 'ma_90',
 'bull_market',
 'year_y',
 'month_y',
 'month_name_y',
 'weekday_y',
 'market_regime',
 'btc_date',
 'volatility_bucket',
 'title_length',
 'title_word_count',
 'fear_title',
 'curiosity_title',
 'opportunity_title',
 'conflict_title',
 'fear_curiosity_title']

In [4]:
def contains_any_word(title, words):
    title = str(title).upper()
    return any(word in title for word in words)

In [5]:
exchange_words = [
    "BINANCE",
    "BYBIT",
    "ZONDA"
]

tutorial_words = [
    "JAK",
    "PORADNIK",
    "KURS",
    "USTAWIĆ",
    "UŻYWAĆ"
]

In [6]:
df["exchange_topic"] = df["title"].apply(
    lambda x: contains_any_word(x, exchange_words)
)

df["tutorial_title"] = df["title"].apply(
    lambda x: contains_any_word(x, tutorial_words)
)

In [7]:
df[
    [
        "exchange_topic",
        "tutorial_title"
    ]
    ].sum()

exchange_topic     37
tutorial_title    130
dtype: int64

In [8]:
df["curiosity_exchange"] = (
    (df["curiosity_title"] == True)
    &
    (df["exchange_topic"] == True)
)

In [9]:
df["curiosity_exchange"].value_counts()

curiosity_exchange
False    696
Name: count, dtype: int64

In [10]:
df.groupby("curiosity_exchange")[
    [
        "view_count",
        "comment_count",
        "engagement_rate"
    ]
    ].mean()

                      view_count  comment_count  engagement_rate
curiosity_exchange
False               11305.443966      51.103448         0.051382

In [11]:
df.to_csv(
    "data/processed/master_dataset_with_content_formulas.csv",
    index=False,
    encoding="utf-8-sig"
)

In [12]:
df[
    [
        "curiosity_title",
        "exchange_topic",
        "curiosity_exchange"
    ]
    ].sum()

curiosity_title       15
exchange_topic        37
curiosity_exchange     0
dtype: int64

In [13]:
df[df["exchange_topic"] == True ][
    [
        "title",
        "curiosity_title",
        "exchange_topic"
    ]
    ].head(20)

,title,curiosity_title,exchange_topic
26,ZONDA CRYPTO: KOLEJNY SPRAWDZIAN DLA PAŃSTWA,False,True
27,NAJWIĘKSZY KRYZYS PO AMBER GOLD - ZONDA CRYPTO,False,True
29,AFERA WOKÓŁ ZONDA CRYPTO,False,True
30,JAK ZONDA CRYPTO OKRADŁA 30 000 POLAKÓW?,False,True
235,🔴 LIVE: CO SIĘ DZIEJE NA BTC ?? Q&A MICA/BYBIT...,False,True
236,🔴 LIVE: CO SIĘ DZIEJE NA BTC ?? Q&A MICA/BYBIT...,False,True
242,KOŃCOWE ODLICZANIE DO STARTU BYBIT EU,False,True
250,ZMIANY W FUNKCJONOWANIU GIEŁDY BYBIT,False,True
279,🔴 LIVE: BINANCE CZEMU ZAMYKA SIĘ W POLSCE ?? K...,False,True
562,KONIEC BINANCE ? 💀 CO DALEJ Z KRYPTO ?,False,True
566,JAK SZYBKO WYPŁACAĆ KRYPTOWALUTY | PORADNIK BY...,False,True
577,🟠 PORADNIK BYBIT 2023 | JAK KORZYSTAĆ Z UNIFIE...,False,True
586,🟢PORADNIK BYBIT | Wszystko Co Musisz Wiedzieć ...,False,True
590,"Problemy Binance, FTX jako nowy gracz?? | MARK...",False,True
593,8.000.000$ w 3 TYGODNIE ! | WSOT BYBIT,False,True
597,5000 zł Za Free Na Airdropie ByBit MANTLE (NIE...,False,True
602,"MetaTrader 4 Na BYBIT, Jak najlepiej tradować ...",False,True
603,Binance vs SEC | Czy Altcoiny Upadną? | MARKET...,False,True
611,Jak zostać VIP-em na ByBit i nie płacić ŻADNYC...,False,True
614,Jak Najprościej Rozliczać się z Wypłat na ByBi...,False,True

In [14]:
top100 = df.sort_values(
    "view_count",
    ascending=False
).head(100)

top100["title"].tolist()

['UJAWNIAM PRAWDĘ O WOJNIE',
 'Poradnik BINANCE FUTURES: Jak Grać Na Giełdzie Kryptowalut Z Dźwignią (2022)',
 'JAK ZONDA CRYPTO OKRADŁA 30 000 POLAKÓW?',
 'UJAWNIAM ILE WOJNA Z IRANEM BĘDZIE WAS KOSZTOWAĆ',
 'PREZYDENT USA CZY PRZESTĘPCA?',
 '10 ZASAD DZIĘKI KTÓRYM ZAROBIŁEM MILION NA KRYPTOWALUTACH !',
 'Poradnik Jak Używać Poziomów Fibonacciego w Analizie Technicznej 2025',
 'TA STRATEGIA DAJE MI 90% WIN RATE NA KRYPTO (PORADNIK)',
 'TO SIĘ KU*WA MUSI ŹLE SKOŃCZYĆ...',
 'SATOSHI NAKAMOTO ZNÓW ONLINE?!',
 'Jak Wpłacić / Wypłacić Pieniądze z Binance (OMIJAJĄC KOSZTA) | Binance Poradnik 2022',
 'PORADNIK Jak Grać Na Giełdzie Kryptowalut Z Dźwignią (BEZPIECZNY SPOSÓB NA 100X)',
 'Najłatwiejsza Metoda Znajdowania Okazji Tradingowych | Poradnik Day Tradingu',
 'Jak Przewidywać Ruchy na Wykresie Kryptowalut (MINI KURS)',
 'Jak Ustawić i Używać STOP LOSS / STOP LIMIT Na Binance | Poradnik Binance 2022',
 'PORADNIK Jak Wpłacić Pieniądze Na ByBit (BEZ KOSZTÓW)',
 'Jak Wypłacić Pieniądze z ByBit | ByBit Poradnik 2022',
 'Poradnik ByBit FUTURES: Jak Grać Na Giełdzie Kryptowalut z Dźwignią (2025)',
 '„ALTCOINY ZAGROŻONE” PIOTR OSTAPOWICZ ZDRADZA SYGNAŁY NA KTÓRE CZEKA',
 'Ta Strategia Daje NAJWYŻSZY Win Rate/ PORADNIK EMA',
 'Jak Zainwestować 1000 zł w Kryptowaluty w 2022 (Zwroty po 8000%)',
 'STRATEGIA WARRENA BUFFETA KTÓRA ZMIENIŁA MOJE ŻYCIE',
 'Jak Legalnie NIE PŁACIĆ PODATKU Od Kryptowalut | Poradnik Podatki Kryptowaluty 2022',
 'ANALIZA FUNDAMENTALNA XRP: POTENCJAŁ 10X CZY BAŃKA SPEKULACYJNA',
 '🚨HALVING BITCOINA: NADCHODZI DUŻA KOREKTA NA KRYPTOWALUTACH?',
 '🔴 LIVE: INAUGURACJA TRUMPA ! JAK ROZEGRAĆ BTC, CO DALEJ Z ALTAMI ??',
 'STRATEGIA DZIĘKI KTÓREJ ZARABIAM NA KRYPTO I FALA ELLIOTTA',
 'MAM 35 LAT. JAK MASZ 20-30 LAT, KONIECZNIE ZOBACZ TEN FILM',
 'TO SIĘ DZIEJE PIERWSZY RAZ W HISTORII BITCOINA. CO TO OZNACZA?!',
 'PILNE: ZATWIERDZENIE XRP TO BĘDZIE POCZĄTEK ALTSEASONU!?',
 'ALTSEASON NADCHODZI: TOP 9 PROJEKTOW',
 'Dzięki Tej Strategi Zarobiłem NAJWIĘCEJ Na Futures!',
 'JAK ZAINWESTOWAĆ 10.000 W KRYPTO I ZAROBIĆ 100.000 w 2024',
 'DLACZEGO ŁADUJE WSZYSTKO W TE ALTCONY...',
 'STRACIŁEM 500.000 PLN NA KRYPTOWALUTACH...OTO CZEGO SIĘ NAUCZYŁEM !',
 'TOP 10 ALTCOINÓW KTÓRE MOCNO SKUPUJE POD HOSSE 2024 !!!',
 'PILNE: USA NIE KUPI BTC! TRUMP SZYKUJE SIĘ NA WIELKĄ PRZECENĘ?',
 'NIE DAJ SIĘ OSZUKAĆ: WIELORYBY PLANUJĄ DOŁEK PRZED OSTATNIĄ POMPĄ?!',
 'UWAŻAJ: WIELORYBY ZNOWU ZROBIĄ WSZYSTKICH W CH*JA NA BITCOINIE',
 'JAK ZARABIAM na ruchach ALTCOINÓW ? | PORADNIK "OD A DO Z" (ICT) CZ.1',
 'Poradnik Linii Wsparcia i Oporu: Jak z Nich Korzystać? (Trading Krypto 2025)',
 'UNIA ZNOWU UTRUDNIA NAM ŻYCIE!',
 'Sekretne narzędzie Wielorybów, zwiększyło moje wyniki FUTURES',
 'JAK WYPRZEDZIĆ 99% LUDZI I STAĆ SIĘ BOGATYM',
 'TRUMPA POJ*BAŁO: POMPUJĄ BAŃKĘ NA KRYPTO!?🚨',
 'UJAWNIAM SYGNAŁY KTÓRE EKSPLODUJĄ RYNEK KRYPTO',
 'UWAGA: BITCOIN I ETH POD OGROMNĄ PRESJĄ ODPŁYWAJĄCEGO KAPITAŁU (UCIEKAĆ\xa0W\xa0STABLE?!)',
 'PILNE: UJAWNIAM JAK ROZGRYWAM ALTSEASON (CO KUPUJE & KIEDY SPRZEDAJE)',
 'UNIA CHCE ZAJ*BAĆ KRYPTO (CO MUSISZ WIEDZIEĆ)',
 'TOP 7 ALTCOINÓW KTÓRE ZROBIĄ 10X PO HALVINGU BITCOINA !',
 'CZAS NA ZABEZPIECZENIE KRYPTOWALUT PRZED NADCHODZĄCĄ BESSĄ!',
 'MÓJ PLAN jak ZAROBIĘ NA HOSSIE w 2024 | Strategia portfela 10x DLA POCZĄTKUJĄCYCH',
 '99% LICZY NA RAJD BTC - TYLKO 1% NA TYM ZAROBI',
 'Świeczki Heiken Ashi - Poradnik Day Tradingu Kryptowalu 2025',
 'NAJWIĘKSZY KRYZYS PO AMBER GOLD - ZONDA CRYPTO',
 'DRUGI SZCZYT TAK JAK 2021 – WSZYSCY WIEMY CZYM TO SIĘ KOŃCZY…',
 'NADCHODZI NAJWIĘKSZA HOSSA NA KRYPTOWALUTACH | KTÓRE ALTCOINY KUPIĆ PRZED WYSTRZAŁEM ?',
 'DANE MÓWIĄ JASNO: MAMY OSTATNIĄ FAZĘ HOSSY - WYKORZYSTAJ TO!',
 'NA TEN PROJEKT PRZEZNACZYŁEM 1.000.000 ZŁ...',
 'UWAGA: RZĄD USA SPOWODUJE POMPĘ ALTCOINÓW ??',
 'TO KONIEC: ZAPLANOWANY KRACH TRUMPA TO POCZĄTEK „CHWILOWEJ” BESSY!?',
 'PILNE: WSZYSTKIE DANE POTWIERDZAJĄ ALTSEASON - DZIAŁAJ TERAZ!',
 'WYCHODZĘ Z RYNKU Z REKORDOWYM ZYSKIEM - CO DALEJ?',
 'MAMY BARDZO WAŻNY SYGNAŁ BITCOINA (IDZIE KOREKTA?)',
 'NIC NIE POWSTRZYMA EKSPLOZJI ALTCOINOW !! CO TERAZ KUPUJE ??',
 'UWAGA: ZACZĄŁEM SPRZEDAWAĆ WSZYSTKIE SWOJE BITCOINY (CO DALEJ?)',
 'PILNE: RYNEK KRWAWI. CZY WCHODZIMY W BESSĘ ?',
 'KU*WA OBUDŹ SIĘ CHŁOPIE',
 'MÓJ PLAN NA ZAROBIENIE MILIONÓW W HOSSIE 2025 (STRATEGIA WYJŚCIA)',
 'TAJEMNICA WIELORYBÓW: MOJA NIEZAWODNA STRATEGIA TRADINGOWA',
 'OSTATNIA SZANSA NA ZAKUP ALTÓW?!',
 'ZROBILI NAS W CH*JA: ALTCOINY MOGĄ MIEĆ DUŻY PROBLEM...',
 'WAŻNE: Kupować ALTY Czy Czekać Na Spadki BTC?🚨',
 'ZACZĘŁA SIĘ OSTRA POMPA - TO NIE CZAS NA GŁUPIE DECYZJE',
 'Top 7 Coinów Z Potencjałem X30 W Najbliższej Hossie',
 'PILNE: TRUMP SZYKUJE POMPĘ ALTCOINÓW (STREFY ZAKUPOWE)',
 'UNIA WŁAŚNIE ZAJE*AŁA KRYPTO - CO MUSISZ ZROBIĆ!!!',
 'ZAPNIJ PASY BO JAK WYJ*BIE…',
 'UWAGA: WIELORYBY SZYKUJĄ PUŁAPKĘ (TO NIE KONIEC SPADKÓW)',
 'ANALIZA: CZEKA NAS WIELKA KOREKTA BTC CZY RAJD NA ATH?',
 'BTC I ETH W STREFIE BESSY - REALIZOWAĆ ZYSKI I UCIEKAĆ?!',
 'WIEDZA DZIĘKI KTÓREJ ZAROBIŁEM MILIONY NA KRYPTO',
 'KONSOLIDACJA NA BTC DOBIEGA KOŃCA... PRZYGOTUJCIE SIĘ NA RUCH!',
 'NAUCZ SIĘ MYŚLEĆ JAK PRO TRADER KRYPTO (TEGO UŻYWAJĄ WIELORYBY)',
 'CZY BITCOIN CZEKA HOSSA DO 2029? (MOJE PREDYKCJE)',
 'Najprostsza Strategia Day Tradingu, Którą Musisz Znać!',
 'NADCHODZI ALTSEASON: Nie Zlekceważ Tych Projektów',
 'PILNE: DANE POKAZUJĄ OGROMNĄ PUŁAPKĘ PRZED KOLEJNYM ATH',
 '🔴 LIVE: CRYPTO SUMMIT, CZY TRUMP SPOMPUJE KRYPTO ??',
 'FORMACJE TECHNICZNE - PORADNIK JAK "PRZEWIDUJE" WYKRESY KRYPTO',
 'JAK ZARABIAM NA KRYPTO STABILNIE I PRZEWIDYWALNIE',
 'Najlepsza Strategia Tradingowa?! COPY TRADING poradnik na ByBit',
 '🚨 NADCHODZI KOREKTA BITCOINA: JAKIE ALTCOINY I KIEDY TRZEBA KUPOWAĆ ?',
 'Kompletny Poradnik TradingView | ANALIZA TECHNICZNA 2025',
 'UWAGA 🚨: NADCHODZI HISTORYCZNY MOMENT DLA XRP ORAZ KRYPTO !!!',
 'A WIĘC TO TAK PLANUJĄ ZNISZCZYĆ KRYPTOWALUTY',
 'BLACKROCK: FIRMA KTÓRA ZRUJNUJE BITCOINA | CO ROBIĆ Z NASZYMI KRYPTOWALUTAMI ??',
 'JAK ROZJ*BAĆ 2025 (BEZ LANIA WODY)',
 'HISTORIA SIĘ POWTARZA…',
 'PILNY SYGNAŁ: WSKAŹNIKI UJAWNIAJĄ PLANOWANĄ KOREKTĘ BTC ??']

In [15]:
for i, title in enumerate(top100["title"], 1):
    print(i, "-", title)

1 - UJAWNIAM PRAWDĘ O WOJNIE
2 - Poradnik BINANCE FUTURES: Jak Grać Na Giełdzie Kryptowalut Z Dźwignią (2022)
3 - JAK ZONDA CRYPTO OKRADŁA 30 000 POLAKÓW?
4 - UJAWNIAM ILE WOJNA Z IRANEM BĘDZIE WAS KOSZTOWAĆ
5 - PREZYDENT USA CZY PRZESTĘPCA?
6 - 10 ZASAD DZIĘKI KTÓRYM ZAROBIŁEM MILION NA KRYPTOWALUTACH !
7 - Poradnik Jak Używać Poziomów Fibonacciego w Analizie Technicznej 2025
8 - TA STRATEGIA DAJE MI 90% WIN RATE NA KRYPTO (PORADNIK)
9 - TO SIĘ KU*WA MUSI ŹLE SKOŃCZYĆ...
10 - SATOSHI NAKAMOTO ZNÓW ONLINE?!
11 - Jak Wpłacić / Wypłacić Pieniądze z Binance (OMIJAJĄC KOSZTA) | Binance Poradnik 2022
12 - PORADNIK Jak Grać Na Giełdzie Kryptowalut Z Dźwignią (BEZPIECZNY SPOSÓB NA 100X)
13 - Najłatwiejsza Metoda Znajdowania Okazji Tradingowych | Poradnik Day Tradingu
14 - Jak Przewidywać Ruchy na Wykresie Kryptowalut (MINI KURS)
15 - Jak Ustawić i Używać STOP LOSS / STOP LIMIT Na Binance | Poradnik Binance 2022
16 - PORADNIK Jak Wpłacić Pieniądze Na ByBit (BEZ KOSZTÓW)
17 - Jak Wypłacić Pieniądze z ByBit | ByBit Poradnik 2022
18 - Poradnik ByBit FUTURES: Jak Grać Na Giełdzie Kryptowalut z Dźwignią (2025)
19 - „ALTCOINY ZAGROŻONE” PIOTR OSTAPOWICZ ZDRADZA SYGNAŁY NA KTÓRE CZEKA
20 - Ta Strategia Daje NAJWYŻSZY Win Rate/ PORADNIK EMA
21 - Jak Zainwestować 1000 zł w Kryptowaluty w 2022 (Zwroty po 8000%)
22 - STRATEGIA WARRENA BUFFETA KTÓRA ZMIENIŁA MOJE ŻYCIE
23 - Jak Legalnie NIE PŁACIĆ PODATKU Od Kryptowalut | Poradnik Podatki Kryptowaluty 2022
24 - ANALIZA FUNDAMENTALNA XRP: POTENCJAŁ 10X CZY BAŃKA SPEKULACYJNA
25 - 🚨HALVING BITCOINA: NADCHODZI DUŻA KOREKTA NA KRYPTOWALUTACH?
26 - 🔴 LIVE: INAUGURACJA TRUMPA ! JAK ROZEGRAĆ BTC, CO DALEJ Z ALTAMI ??
27 - STRATEGIA DZIĘKI KTÓREJ ZARABIAM NA KRYPTO I FALA ELLIOTTA
28 - MAM 35 LAT. JAK MASZ 20-30 LAT, KONIECZNIE ZOBACZ TEN FILM
29 - TO SIĘ DZIEJE PIERWSZY RAZ W HISTORII BITCOINA. CO TO OZNACZA?!
30 - PILNE: ZATWIERDZENIE XRP TO BĘDZIE POCZĄTEK ALTSEASONU!?
31 - ALTSEASON NADCHODZI: TOP 9 PROJEKTOW
32 - Dzięki Tej Strategi Zarobiłem NAJWIĘCEJ Na Futures!
33 - JAK ZAINWESTOWAĆ 10.000 W KRYPTO I ZAROBIĆ 100.000 w 2024
34 - DLACZEGO ŁADUJE WSZYSTKO W TE ALTCONY...
35 - STRACIŁEM 500.000 PLN NA KRYPTOWALUTACH...OTO CZEGO SIĘ NAUCZYŁEM !
36 - TOP 10 ALTCOINÓW KTÓRE MOCNO SKUPUJE POD HOSSE 2024 !!!
37 - PILNE: USA NIE KUPI BTC! TRUMP SZYKUJE SIĘ NA WIELKĄ PRZECENĘ?
38 - NIE DAJ SIĘ OSZUKAĆ: WIELORYBY PLANUJĄ DOŁEK PRZED OSTATNIĄ POMPĄ?!
39 - UWAŻAJ: WIELORYBY ZNOWU ZROBIĄ WSZYSTKICH W CH*JA NA BITCOINIE
40 - JAK ZARABIAM na ruchach ALTCOINÓW ? | PORADNIK "OD A DO Z" (ICT) CZ.1
41 - Poradnik Linii Wsparcia i Oporu: Jak z Nich Korzystać? (Trading Krypto 2025)
42 - UNIA ZNOWU UTRUDNIA NAM ŻYCIE!
43 - Sekretne narzędzie Wielorybów, zwiększyło moje wyniki FUTURES
44 - JAK WYPRZEDZIĆ 99% LUDZI I STAĆ SIĘ BOGATYM
45 - TRUMPA POJ*BAŁO: POMPUJĄ BAŃKĘ NA KRYPTO!?🚨
46 - UJAWNIAM SYGNAŁY KTÓRE EKSPLODUJĄ RYNEK KRYPTO
47 - UWAGA: BITCOIN I ETH POD OGROMNĄ PRESJĄ ODPŁYWAJĄCEGO KAPITAŁU (UCIEKAĆ W STABLE?!)
48 - PILNE: UJAWNIAM JAK ROZGRYWAM ALTSEASON (CO KUPUJE & KIEDY SPRZEDAJE)
49 - UNIA CHCE ZAJ*BAĆ KRYPTO (CO MUSISZ WIEDZIEĆ)
50 - TOP 7 ALTCOINÓW KTÓRE ZROBIĄ 10X PO HALVINGU BITCOINA !
51 - CZAS NA ZABEZPIECZENIE KRYPTOWALUT PRZED NADCHODZĄCĄ BESSĄ!
52 - MÓJ PLAN jak ZAROBIĘ NA HOSSIE w 2024 | Strategia portfela 10x DLA POCZĄTKUJĄCYCH
53 - 99% LICZY NA RAJD BTC - TYLKO 1% NA TYM ZAROBI
54 - Świeczki Heiken Ashi - Poradnik Day Tradingu Kryptowalu 2025
55 - NAJWIĘKSZY KRYZYS PO AMBER GOLD - ZONDA CRYPTO
56 - DRUGI SZCZYT TAK JAK 2021 – WSZYSCY WIEMY CZYM TO SIĘ KOŃCZY…
57 - NADCHODZI NAJWIĘKSZA HOSSA NA KRYPTOWALUTACH | KTÓRE ALTCOINY KUPIĆ PRZED WYSTRZAŁEM ?
58 - DANE MÓWIĄ JASNO: MAMY OSTATNIĄ FAZĘ HOSSY - WYKORZYSTAJ TO!
59 - NA TEN PROJEKT PRZEZNACZYŁEM 1.000.000 ZŁ...
60 - UWAGA: RZĄD USA SPOWODUJE POMPĘ ALTCOINÓW ??
61 - TO KONIEC: ZAPLANOWANY KRACH TRUMPA TO POCZĄTEK „CHWILOWEJ” BESSY!?
62 - PILNE: WSZYSTKIE DANE POTWIERDZAJĄ ALTSEASON - DZIAŁAJ TERAZ!
63 - WYCHODZĘ Z RYNKU Z REKORDOWYM ZYSKIEM - CO DALEJ?
64 - MAMY BARDZO WAŻNY SYGNAŁ BITCOINA (IDZIE KOREKTA?)
65 - NIC NIE POWSTRZYMA EKSPLOZJI ALTCOINOW !! CO TERAZ KUPUJE ??
66 - UWAGA: ZACZĄŁEM SPRZEDAWAĆ WSZYSTKIE SWOJE BITCOINY (CO DALEJ?)
67 - PILNE: RYNEK KRWAWI. CZY WCHODZIMY W BESSĘ ?
68 - KU*WA OBUDŹ SIĘ CHŁOPIE
69 - MÓJ PLAN NA ZAROBIENIE MILIONÓW W HOSSIE 2025 (STRATEGIA WYJŚCIA)
70 - TAJEMNICA WIELORYBÓW: MOJA NIEZAWODNA STRATEGIA TRADINGOWA
71 - OSTATNIA SZANSA NA ZAKUP ALTÓW?!
72 - ZROBILI NAS W CH*JA: ALTCOINY MOGĄ MIEĆ DUŻY PROBLEM...
73 - WAŻNE: Kupować ALTY Czy Czekać Na Spadki BTC?🚨
74 - ZACZĘŁA SIĘ OSTRA POMPA - TO NIE CZAS NA GŁUPIE DECYZJE
75 - Top 7 Coinów Z Potencjałem X30 W Najbliższej Hossie
76 - PILNE: TRUMP SZYKUJE POMPĘ ALTCOINÓW (STREFY ZAKUPOWE)
77 - UNIA WŁAŚNIE ZAJE*AŁA KRYPTO - CO MUSISZ ZROBIĆ!!!
78 - ZAPNIJ PASY BO JAK WYJ*BIE…
79 - UWAGA: WIELORYBY SZYKUJĄ PUŁAPKĘ (TO NIE KONIEC SPADKÓW)
80 - ANALIZA: CZEKA NAS WIELKA KOREKTA BTC CZY RAJD NA ATH?
81 - BTC I ETH W STREFIE BESSY - REALIZOWAĆ ZYSKI I UCIEKAĆ?!
82 - WIEDZA DZIĘKI KTÓREJ ZAROBIŁEM MILIONY NA KRYPTO
83 - KONSOLIDACJA NA BTC DOBIEGA KOŃCA... PRZYGOTUJCIE SIĘ NA RUCH!
84 - NAUCZ SIĘ MYŚLEĆ JAK PRO TRADER KRYPTO (TEGO UŻYWAJĄ WIELORYBY)
85 - CZY BITCOIN CZEKA HOSSA DO 2029? (MOJE PREDYKCJE)
86 - Najprostsza Strategia Day Tradingu, Którą Musisz Znać!
87 - NADCHODZI ALTSEASON: Nie Zlekceważ Tych Projektów
88 - PILNE: DANE POKAZUJĄ OGROMNĄ PUŁAPKĘ PRZED KOLEJNYM ATH
89 - 🔴 LIVE: CRYPTO SUMMIT, CZY TRUMP SPOMPUJE KRYPTO ??
90 - FORMACJE TECHNICZNE - PORADNIK JAK "PRZEWIDUJE" WYKRESY KRYPTO
91 - JAK ZARABIAM NA KRYPTO STABILNIE I PRZEWIDYWALNIE
92 - Najlepsza Strategia Tradingowa?! COPY TRADING poradnik na ByBit
93 - 🚨 NADCHODZI KOREKTA BITCOINA: JAKIE ALTCOINY I KIEDY TRZEBA KUPOWAĆ ?
94 - Kompletny Poradnik TradingView | ANALIZA TECHNICZNA 2025
95 - UWAGA 🚨: NADCHODZI HISTORYCZNY MOMENT DLA XRP ORAZ KRYPTO !!!
96 - A WIĘC TO TAK PLANUJĄ ZNISZCZYĆ KRYPTOWALUTY
97 - BLACKROCK: FIRMA KTÓRA ZRUJNUJE BITCOINA | CO ROBIĆ Z NASZYMI KRYPTOWALUTAMI ??
98 - JAK ROZJ*BAĆ 2025 (BEZ LANIA WODY)
99 - HISTORIA SIĘ POWTARZA…
100 - PILNY SYGNAŁ: WSKAŹNIKI UJAWNIAJĄ PLANOWANĄ KOREKTĘ BTC ??